### ISSUE TITLE
Urgent: Issue with Connecting to SkySpark 3.1.1

### ISSUE THREAD

**Issue by vnathoo** [IOT-DSA/dslink-java-haystack#18]
Cannot current to the latest version of skyspark. The log file gives the following error:
[2021-11-14 23:57:57.396011] 2021-11-14 23:57:57.394 [Thread-6] WARN org.dsa.iot.haystack.helpers.ConnectionHelper - Unable to connect to https://server.com/api/projectName : name : 
[2021-11-14 23:57:57.397380] org.projecthaystack.UnknownNameException: name
[2021-11-14 23:57:57.397406] 	at org.projecthaystack.HRow.get(HRow.java:46)
[2021-11-14 23:57:57.397419] 	at org.projecthaystack.HDict.get(HDict.java:49)
[2021-11-14 23:57:57.397431] 	at org.dsa.iot.haystack.helpers.ConnectionHelper$Connector.run(ConnectionHelper.java:240)
[2021-11-14 23:57:57.397441] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-11-14 23:57:57.397452] 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2021-11-14 23:57:57.397462] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2021-11-14 23:57:57.397474] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-11-14 23:57:57.397485] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-11-14 23:57:57.397495] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-11-14 23:57:57.397506]

**Comment by vnathoo** [comment]
Fixed.
